### ISSUE TITLE
TODO Tracker

### ISSUE THREAD

**Issue by Vija02** [Vija02/TheOpenPresenter#1]
- Management
  - [ ] Organization settings pages (public flag)
  - [ ] Media management
  - [ ] Better project management (name, category, tagging, delete, etc)
- Remote
  - [ ] Scene management (reorder, delete, rename)
  - [ ] Active scene indication
  - [ ] Active audio indication
  - [ ] Error notification
  - [ ] Renderer readiness indication
  - [ ] Renderer audio blockage indication
  - [ ] Button to reload renderer
  - [ ] Style update
- Renderer
  - [ ] Keyboard handling
- Plugin API
  - [ ] Cleanup/tidy server APIs
  - [ ] Handle media permission better
  - [ ] Add access to database
  - [ ] Icons for plugins
- Plugins
  - Lyrics (MyWorshipList)
    - [ ] Standardize our own format
    - [ ] Preview when editing song
    - [ ] Add more importer & generalize plugin to be Lyrics
  - Slides (Google drive)
    - [ ] Notify when slides is out of date
    - [ ] Handle different regions
    - [ ] Add note about video support
    - [ ] Move renderer to use Collabora
    - [ ] Add other sources & generalize plugin
  - Audio recorder
    - [ ] Handle error & retry better
    - [ ] Save locally for backup & send at the end if needed
    - [ ] Audio waveform for playback
    - [ ] Option to cut silence
  - Radio
    - [ ] Update to general music player
    - [ ] Add other sources
  - Video player
    - [ ] Playlist support
    - [ ] Pause on exit
    - [ ] Get duration in a more robust way
